args <- commandArgs(trailingOnly=TRUE)
root <- args[[1]]
dest <- root
wb <- file.path(dest, 'Source_Data_Revised.xlsx')
fig_dir <- file.path(dest, 'Analysis_Code/figure_outputs')
dir.create(fig_dir, showWarnings=FALSE)
dir.create(file.path(root,'Analysis_Code/figure_outputs'),showWarnings=FALSE,recursive=TRUE)
suppressPackageStartupMessages({library(ggplot2);library(dplyr);library(tidyr);library(readr);library(readxl);library(patchwork);library(cowplot);library(magick)})
source(file.path(root,'Analysis_Code/00_common_theme.R'))
source(file.path(root,'Analysis_Code/sheet_io.R'))
theme_set(theme_phenotype(8) + theme(text=element_text(family='sans'), axis.title=element_text(size=8),axis.text=element_text(size=7),strip.text=element_text(size=9,face='bold'),legend.title=element_text(size=7.5,face='bold'),legend.text=element_text(size=7),plot.margin=margin(8,3,3,8),panel.grid.major=element_line(colour='#EBEBEB',linewidth=.35)))
ages <- c('1-year','2-year')
format_group <- function(x) x %>% mutate(genotype=factor(genotype,levels=c('DD','GG','GD')),age=factor(age,levels=1:2,labels=ages))
surv <- read_sheet(wb,sheet='Current_Survival_Tanks') %>% format_group()
heart <- read_sheet(wb,sheet='Current_Cardiac_Means') %>% format_group()
cts <- read_sheet(wb,sheet='Current_Survival_Contrasts') %>% mutate(age=factor(age,levels=1:2,labels=ages),label=sprintf('P = %.4f',P_Holm_two),y=c(24,69))
long <- surv %>% pivot_longer(cols=c(s0,s24,s48,s72,s96),names_to='time',values_to='value') %>% mutate(time=as.numeric(sub('s','',time)))
s <- long %>% group_by(age,genotype,time) %>% summarise(mean=mean(value),SEM=sd(value)/sqrt(n()),.groups='drop')
pA <- ggplot(s,aes(time,mean,colour=genotype,group=genotype))+geom_line(linewidth=.65)+geom_point(size=1.5)+geom_errorbar(aes(ymin=pmax(0,mean-SEM),ymax=pmin(100,mean+SEM)),width=3,linewidth=.3,alpha=.7)+facet_wrap(~age)+scale_colour_manual(values=col_genotype,name='Genotype')+scale_x_continuous(breaks=c(0,24,48,72,96))+scale_y_continuous(breaks=seq(0,100,25),limits=c(0,105))+labs(x='Time post-injection (h)',y='Survival rate (%)')+theme(legend.position='bottom')
heart_bar <- function(metric,label) ggplot(heart,aes(genotype,.data[[metric]],fill=genotype))+geom_col(width=.65,alpha=.85)+facet_wrap(~age)+scale_fill_manual(values=col_genotype,guide='none')+scale_y_continuous(limits=c(0,ifelse(metric=='CBTB_min',1100,1500)),expand=expansion(mult=c(0,.02)))+labs(x='Genotype',y=label)
pB <- heart_bar('CBTB_min','CBTB (min)');pD <- heart_bar('CZTB_min','CZTB (min)')
ss <- surv %>% group_by(age,genotype) %>% summarise(mean=mean(s96),SEM=sd(s96)/sqrt(n()),.groups='drop')
pC <- ggplot(ss,aes(genotype,mean,fill=genotype))+geom_col(width=.65,alpha=.85)+geom_errorbar(aes(ymin=pmax(0,mean-SEM),ymax=mean+SEM),width=.2,linewidth=.35)+geom_point(data=surv,aes(y=s96),position=position_jitter(width=.1,height=0,seed=24),colour='grey25',alpha=.7,size=1.3)+facet_wrap(~age)+scale_fill_manual(values=col_genotype,guide='none')+geom_text(data=cts,aes(x=2,y=y,label=label),inherit.aes=FALSE,size=2.5,fontface='italic')+scale_y_continuous(limits=c(0,80),breaks=seq(0,80,20))+labs(x='Genotype',y='Survival rate at 96 h (%)')
# 仅示意定义，不属于实验测量值；保留原灰色曲线/红蓝垂线体系。
set.seed(42); tt<-seq(0,1500,5); bpm<-pmax(0,ifelse(tt<=600,82,ifelse(tt<1100,82*(1100-tt)/500,2))+rnorm(length(tt),0,2))
pE<-ggplot(data.frame(tt,bpm),aes(tt,bpm))+geom_line(colour='grey40',linewidth=.4)+geom_vline(xintercept=600,linetype='dashed',colour='#E41A1C',linewidth=.6)+geom_vline(xintercept=1100,linetype='dashed',colour='#377EB8',linewidth=.6)+annotate('text',x=600,y=97,label='CBTB',colour='#E41A1C',fontface='bold',size=3)+annotate('text',x=1230,y=16,label='CZTB',colour='#377EB8',fontface='bold',size=3)+scale_x_continuous(breaks=seq(0,1500,500))+scale_y_continuous(limits=c(0,102),breaks=seq(0,100,25))+labs(x='Time post-injection (min)',y='Heart rate (BPM)')
pF<-ggplot(heart,aes(CBTB_min,CZTB_min,colour=age,shape=genotype))+geom_point(size=3)+scale_colour_manual(values=col_age,name='Age')+scale_shape_manual(values=c(DD=16,GG=17,GD=15),name='Genotype')+labs(x='CBTB (min)',y='CZTB (min)')+theme(legend.position='right')
fig2<-wrap_plots(pA,pB,pC,pD,pE,pF,ncol=2)+plot_annotation(tag_levels='A')&theme(plot.tag=element_text(size=15,face='plain'),plot.tag.position=c(0,1))
save_figure<-function(fig,name,w,h){
 ggsave(file.path(fig_dir,paste0(name,'.pdf')),fig,width=w,height=h,units='mm',device=cairo_pdf,bg='white')
 ggsave(file.path(fig_dir,paste0(name,'.png')),fig,width=w,height=h,units='mm',dpi=600,device=ragg::agg_png,bg='white')
 ggsave(file.path(fig_dir,paste0(name,'.tiff')),fig,width=w,height=h,units='mm',dpi=600,device=ragg::agg_tiff,compression='lzw',bg='white')
 ggsave(file.path(fig_dir,paste0(name,'_preview.png')),fig,width=w,height=h,units='mm',dpi=180,device=ragg::agg_png,bg='white')
}
save_figure(fig2,'Figure_2_revised',180,190)

flow<-read_sheet(wb,sheet='Current_Flow_Summary')%>%mutate(Genotype=factor(Genotype,levels=c('DD','GG','GD')),Age=factor(Age,levels=ages))
flow_plot<-function(metric,label,scale=1) ggplot(filter(flow,measure==metric),aes(Time,mean/scale,colour=Genotype,linetype=Age,group=interaction(Genotype,Age)))+geom_line(linewidth=.6)+geom_point(size=1.5)+geom_errorbar(aes(ymin=pmax(0,(mean-SEM)/scale),ymax=(mean+SEM)/scale),width=5,linewidth=.25,alpha=.7)+scale_colour_manual(values=col_genotype,name='Genotype')+scale_linetype_manual(values=c('1-year'='solid','2-year'='dashed'),name='Age')+scale_x_continuous(breaks=c(0,24,48,96,168))+labs(x='Time (h)',y=label)+theme(legend.position='none')
fA<-flow_plot('THC','THC (fold of baseline)');fB<-flow_plot('MOR','Haemocyte mortality (%)');fC<-flow_plot('PHA','Phagocytosis (%)');fD<-flow_plot('ROS',expression('ROS ('*10^6*' fluorescence a.u.)'),1e6)
# 原稿组织学面板保持连续图像、配色、顺序、标尺；只裁掉其他统计面板。
cached_hist<-file.path(root,'Analysis_Code/figure_inputs/histology_panels_EF.png')
if(file.exists(cached_hist)) hist<-image_read(cached_hist) else {
 orig<-image_read(file.path(root,'Analysis_Code/figure_inputs/image3.tif'))
 info<-image_info(orig);ww<-info$width[1];hh<-info$height[1]
 hist<-image_crop(orig,geometry_area(ww,round(hh*.344),0,round(hh*.408)))
}
image_write(hist,file.path(fig_dir,'original_histology_panels_EF.png'))
histplot<-ggdraw()+draw_image(as.raster(hist),x=0,y=0,width=1,height=1)
histdf<-read_csv(file.path(root,'Analysis_Code/figure_inputs/Histology_descriptive.csv'),show_col_types=FALSE)%>%mutate(age=factor(ifelse(grepl('1',age_class),1,2),levels=1:2,labels=ages),genotype=factor(genotype,levels=c('DD','GG','GD')),tissue=factor(tissue,levels=c('Foot muscle','Digestive gland','Gill','Mantle')))
ts<-histdf%>%rowwise()%>%mutate(time=list(c(0,24,48,96,168)),value=list(as.numeric(strsplit(gsub('[^0-9.,-]','',recorded_proportions),',')[[1]])))%>%ungroup()%>%unnest(c(time,value))
stopifnot(nrow(ts)==120, !anyNA(ts$value))
fG<-ggplot(ts,aes(time,value*100,colour=genotype,linetype=age,group=interaction(genotype,age)))+geom_line(linewidth=.5)+geom_point(size=1.2)+facet_wrap(~tissue,ncol=2)+scale_colour_manual(values=col_genotype,name='Genotype')+scale_linetype_manual(values=c('1-year'='solid','2-year'='dashed'),name='Age')+scale_x_continuous(breaks=c(0,48,96,168))+scale_y_continuous(limits=c(0,103),breaks=c(0,50,100))+labs(x='Time (h)',y='Lesion-positive proportion (%)')+theme(legend.position='none',strip.text=element_text(size=8.5,face='bold'))
fH<-ggplot(histdf,aes(genotype,tissue,fill=AUC_proportion_h))+geom_tile(colour='white',linewidth=.3)+geom_text(aes(label=sprintf('%.0f',AUC_proportion_h),colour=AUC_proportion_h>95),size=2.3)+scale_colour_manual(values=c('FALSE'='black','TRUE'='white'),guide='none')+scale_fill_gradientn(colours=c('#fff5f0','#fcbba1','#fb6a4a','#a50f15'),limits=c(0,168),breaks=c(0,50,100,150),name='AUC\n(proportion × h)')+scale_y_discrete(limits=rev(levels(histdf$tissue)))+facet_wrap(~age,nrow=1)+labs(x='Genotype',y=NULL)+theme(panel.grid=element_blank(),axis.text.y=element_text(size=7),legend.key.height=unit(5,'mm'),legend.key.width=unit(3,'mm'),legend.title=element_text(size=7))
legend <- cowplot::get_legend(fA+theme(legend.position='bottom',legend.direction='horizontal'))
top<-plot_grid(fA,fB,fC,fD,ncol=2,labels=c('A','B','C','D'),label_size=15,label_fontface='plain',hjust=0,vjust=1)
bottom<-plot_grid(fG,fH,ncol=2,labels=c('G','H'),label_size=15,label_fontface='plain',hjust=0,vjust=1)
fig3<-plot_grid(top,histplot,bottom,ggdraw(legend),ncol=1,rel_heights=c(2.0,1.65,1.15,.16))
save_figure(fig3,'Figure_3_revised',180,224)
writeLines(capture.output(sessionInfo()),file.path(fig_dir,'R_figure_sessionInfo.txt'))
print(image_info(hist));cat('Figures 2 and 3 exported\n');print(warnings())
